Refactoring methods and endpoints using SRP
angolarti/pluralsiscloud pull request #22
Opened 2023-08-13 21:37 UTC by manuelcunga

2023-08-15 07:09 UTC, angolarti requested changes
Bom dia. Lazaro!

Para as funções de operações sem regras de negócio (usecases) não necessariamente devemos segmentá-las, desse jeito elas fazem parte de um escopo de operações do container cria apenas uma Struct Controller que vai agrupar todas as operações de request e response

2023-08-15 12:54 UTC, manuelcunga commented
> Bom dia. Lazaro!
> 
> Para as funções de operações sem regras de negócio (usecases) não necessariamente devemos segmentá-las, desse jeito elas fazem parte de um escopo de operações do container cria apenas uma Struct Controller que vai agrupar todas as operações de request e response

Ok faz sentido, vou fazer isso!

2024-03-20 06:41 UTC, angolarti approved these changes

2024-03-20 06:44 UTC, angolarti approved these changes

2024-03-20 06:44 UTC, closed without merging